### ISSUE TITLE
Can certificates be requested using the SAN method, with a single submission?

### ISSUE THREAD

**Issue by mayenpotsu** [tinkernels/zerossl-ip-cert#12]
After testing on zerossl web portal, it is possible to include multiple domains of different in a single certificate (with only one key file).
    Is it possible to perform the same operation using a script?

**Comment by tinkernels** [comment]
No, this tool can only issue one cert for for a single ipv4 address once.

**Comment by mayenpotsu** [comment]
It is possible  in future versions support SAN functionality?

**Comment by tinkernels** [comment]
> It is possible in future versions support SAN functionality?

Are you tring to issue cert with ***ips & domains*** as CN or cert with ***multiple ips*** as CN?

FYI: this tool is mainly for cert with ip, if you just want multple domains as CN in cert, you can use ***certbot*** or alternatives, a official tool [zerossl-bot](https://github.com/zerossl/zerossl-bot) is provided.
