### ISSUE TITLE
Read all certificates every time

### ISSUE THREAD

**Issue by njj0121** [tinkernels/zerossl-ip-cert#14]
现在每次在新服务器上运行时会读取所有的证书。
Now all certificates are read every time when running on a new server.
我认为这一步有些多余，现在已经每次读取40多个证书了。
I think this step is a bit redundant, and now I am reading more than 40 certificates each time.
这包括Issued、Expired、Draft以及其他所有不是acme签发的证书。
This includes Issued, Expired, Draft and all other certificates not issued by acme.

**Comment by tinkernels** [comment]
you can set this option to false in `config.yml` and should escape from retrieving all certs.

```yaml
...
cleanUnfinished: false # Clean zerossl certificates that are not finished issuing.
...
```
