### ISSUE TITLE
Pending at zerossl_client.go:207: Cleaning unfinished certificates

### ISSUE THREAD

**Issue by xm9572** [tinkernels/zerossl-ip-cert#15]
My log:

2023/09/27 00:07:45 main.go:79: Using config file: /var/local/zerossl/config1.yaml
2023/09/27 00:07:45 main.go:110: Issuing certs
2023/09/27 00:07:45 main.go:112: Issuing cert for domain: 38.163.?.?
2023/09/27 00:07:45 main.go:130: Cert for domain 38.163.?.? does not exist, try issue.
2023/09/27 00:07:45 zerossl_client.go:207: Cleaning unfinished certificates

Stay here forever.
I have more than 100 IPs in total, and it happens to be the 100th one that stops responding. What is the reason?

**Comment by tinkernels** [comment]
Fixed by #17
