### ISSUE TITLE
Stuck at zerossl_client.go:207: Cleaning unfinished certificates

### ISSUE THREAD

**Issue by xm9572** [tinkernels/zerossl-ip-cert#19]
My server cannot use zerossl-ip-cert. Whether I am adding or renewing certificates, it is stuck at zerossl_client.go:207: Cleaning unfinished certificates

**Comment by xm9572** [comment]
How to manually clear unfinished certificate files? I deleted the current.yaml and temp folders in the directory, but the same thing happened.

**Comment by tinkernels** [comment]
> How to manually clear unfinished certificate files? I deleted the current.yaml and temp folders in the directory, but the same thing happened.

This should already be fixed by #17 3423a40d730f7f2760cefc35604d5973369ec0f9
