### ISSUE TITLE
Type:invalid_api_function Details:map[]

### ISSUE THREAD

**Issue by lbroot** [tinkernels/zerossl-ip-cert#6]
2022/04/24 05:12:03 main.go:187: Writing private key to file /var/local/zerossl/temp/privkey.pem
2022/04/24 05:12:03 main.go:193: Creating cert for ****
2022/04/24 05:12:03 main.go:200: cert info: {ID: Type: CommonName: AdditionalDomains: Created: Expires: Status: ValidationType: ValidationEmails: ReplacementFor: Validation:{EmailValidation:map[] OtherMethods:map[]}}
2022/04/24 05:12:03 main.go:274: try make verify hook file executable
2022/04/24 05:12:03 main.go:211: domains verification result: {Success:false Error:{Code:103 Type:invalid_api_function Details:map[]}}
2022/04/24 05:12:09 main.go:219: cert info: {ID: Type: CommonName: AdditionalDomains: Created: Expires: Status: ValidationType: ValidationEmails: ReplacementFor: Validation:{EmailValidation:map[] OtherMethods:map[]}}

**Comment by lbroot** [comment]
It seems  hook file cant execute correctly

**Comment by lbroot** [comment]
solved

**Comment by zyp0209** [comment]
How did you solve it? thanks

**Comment by tinkernels** [comment]
> How did you solve it? thanks

Have you configured zerossl api key from your zerossl account profile? https://github.com/tinkernels/zerossl-ip-cert/blob/99665d2bbb648a932da8d274dd552feb4b011637/exec/sample-config.yaml#L10

**Comment by lbroot** [comment]
zerossl can only create up to three orders for free, log in to the official website of zerossl to cancel the created but unverified order, otherwise you cannot create a new order.

**Comment by lbroot** [comment]
zerossl can only create up to three orders for free, log in to the official website of zerossl to cancel the created but unverified order, otherwise you cannot create a new order.
