### ISSUE TITLE
Only 3 certificates can be issued per IP address.

### ISSUE THREAD

**Issue by Xeath** [tinkernels/zerossl-ip-cert#9]
Only 3 certificates can be issued per IP address.
每个 IP 地址只能颁发 3 个证书。
Instead of binding accounts, binding IP addresses.
不是绑定账户，而是绑定 IP 地址。

换账户也没用，重要业务赶紧换回去域名，或者使用付费服务。

**Comment by tinkernels** [comment]
Here is not the right place to complain about zerossl service limit, you may have to reach zerossl.
